using ClosedXML.Excel;
using DuctSupportAddin.Models;

namespace DuctSupportAddin.Core.Export;

/// <summary>
/// Exports support data to Excel format.
/// </summary>
public class ExcelExporter
{
    /// <summary>
    /// Export report data to Excel file.
    /// </summary>
    public void Export(ReportData data, string filePath)
    {
        using var workbook = new XLWorkbook();
        
        // Summary sheet
        CreateSummarySheet(workbook, data);
        
        // Level breakdown sheet
        CreateLevelSheet(workbook, data);
        
        // Support schedule sheet
        CreateScheduleSheet(workbook, data);
        
        // Load summary sheet
        CreateLoadSheet(workbook, data);
        
        workbook.SaveAs(filePath);
    }
    
    /// <summary>
    /// Create summary sheet.
    /// </summary>
    private void CreateSummarySheet(XLWorkbook workbook, ReportData data)
    {
        var sheet = workbook.Worksheets.Add("Summary");
        
        // Header
        sheet.Cell("A1").Value = "DUCT SUPPORT PLACEMENT REPORT";
        sheet.Cell("A1").Style.Font.Bold = true;
        sheet.Cell("A1").Style.Font.FontSize = 16;
        
        // Project info
        int row = 3;
        sheet.Cell(row, 1).Value = "Project:";
        sheet.Cell(row, 2).Value = data.ProjectName;
        row++;
        
        sheet.Cell(row, 1).Value = "Project Number:";
        sheet.Cell(row, 2).Value = data.ProjectNumber;
        row++;
        
        sheet.Cell(row, 1).Value = "Generated:";
        sheet.Cell(row, 2).Value = data.GeneratedDate.ToString("yyyy-MM-dd HH:mm");
        row++;
        
        sheet.Cell(row, 1).Value = "Generated By:";
        sheet.Cell(row, 2).Value = data.GeneratedBy;
        row += 2;
        
        // Configuration
        sheet.Cell(row, 1).Value = "CONFIGURATION";
        sheet.Cell(row, 1).Style.Font.Bold = true;
        row++;
        
        sheet.Cell(row, 1).Value = "Spacing Standard:";
        sheet.Cell(row, 2).Value = data.SpacingStandard;
        row++;
        
        sheet.Cell(row, 1).Value = "Spacing Adjustment:";
        sheet.Cell(row, 2).Value = $"{data.SpacingPercentage}%";
        row++;
        
        sheet.Cell(row, 1).Value = "Insulation Considered:";
        sheet.Cell(row, 2).Value = data.IncludesInsulation ? "Yes" : "No";
        row += 2;
        
        // Statistics
        sheet.Cell(row, 1).Value = "STATISTICS";
        sheet.Cell(row, 1).Style.Font.Bold = true;
        row++;
        
        sheet.Cell(row, 1).Value = "Total Supports Placed:";
        sheet.Cell(row, 2).Value = data.TotalSupports;
        row++;
        
        sheet.Cell(row, 1).Value = "• Ceiling Mounted:";
        sheet.Cell(row, 2).Value = data.CeilingSupports;
        row++;
        
        sheet.Cell(row, 1).Value = "• Ground Supports:";
        sheet.Cell(row, 2).Value = data.GroundSupports;
        row++;
        
        sheet.Cell(row, 1).Value = "• Wall Supports:";
        sheet.Cell(row, 2).Value = data.WallSupports;
        row++;
        
        sheet.Cell(row, 1).Value = "• Vertical Supports:";
        sheet.Cell(row, 2).Value = data.VerticalSupports;
        row++;
        
        sheet.Cell(row, 1).Value = "Total Calculated Load:";
        sheet.Cell(row, 2).Value = $"{data.TotalLoadKg:N0} kg";
        row += 2;
        
        // Skipped
        sheet.Cell(row, 1).Value = "Skipped Due to Fittings:";
        sheet.Cell(row, 2).Value = data.SkippedDueToFittings;
        row++;
        
        sheet.Cell(row, 1).Value = "Skipped Due to Existing:";
        sheet.Cell(row, 2).Value = data.SkippedDueToExisting;
        row++;
        
        sheet.Cell(row, 1).Value = "Clashes Detected:";
        sheet.Cell(row, 2).Value = data.ClashesDetected;
        
        // Format
        sheet.Column(1).Width = 25;
        sheet.Column(2).Width = 30;
    }
    
    /// <summary>
    /// Create level breakdown sheet.
    /// </summary>
    private void CreateLevelSheet(XLWorkbook workbook, ReportData data)
    {
        var sheet = workbook.Worksheets.Add("By Level");
        
        // Header
        sheet.Cell("A1").Value = "Level";
        sheet.Cell("B1").Value = "Support Count";
        sheet.Cell("C1").Value = "Total Load (kg)";
        
        var headerRow = sheet.Row(1);
        headerRow.Style.Font.Bold = true;
        headerRow.Style.Fill.BackgroundColor = XLColor.LightGray;
        
        // Data
        int row = 2;
        foreach (var level in data.LevelSummaries.OrderBy(l => l.LevelName))
        {
            sheet.Cell(row, 1).Value = level.LevelName;
            sheet.Cell(row, 2).Value = level.SupportCount;
            sheet.Cell(row, 3).Value = level.TotalLoadKg;
            row++;
        }
        
        // Totals
        sheet.Cell(row, 1).Value = "TOTAL";
        sheet.Cell(row, 1).Style.Font.Bold = true;
        sheet.Cell(row, 2).Value = data.TotalSupports;
        sheet.Cell(row, 3).Value = data.TotalLoadKg;
        
        sheet.Columns().AdjustToContents();
    }
    
    /// <summary>
    /// Create detailed schedule sheet.
    /// </summary>
    private void CreateScheduleSheet(XLWorkbook workbook, ReportData data)
    {
        var sheet = workbook.Worksheets.Add("Support Schedule");
        
        // Headers
        string[] headers = 
        {
            "Mark", "Type", "Level", "Grid", 
            "X (mm)", "Y (mm)", "Z (mm)",
            "Duct Width (mm)", "Support Width (mm)", 
            "Rod Length (mm)", "Support Height (mm)",
            "Load (kg)", "Recommended Rod", "Clash Status"
        };
        
        for (int i = 0; i < headers.Length; i++)
        {
            sheet.Cell(1, i + 1).Value = headers[i];
        }
        
        var headerRow = sheet.Row(1);
        headerRow.Style.Font.Bold = true;
        headerRow.Style.Fill.BackgroundColor = XLColor.LightGray;
        
        // Data
        int row = 2;
        foreach (var support in data.Supports.OrderBy(s => s.Mark))
        {
            sheet.Cell(row, 1).Value = support.Mark;
            sheet.Cell(row, 2).Value = support.Type;
            sheet.Cell(row, 3).Value = support.LevelName;
            sheet.Cell(row, 4).Value = support.GridLocation;
            sheet.Cell(row, 5).Value = Math.Round(support.X, 0);
            sheet.Cell(row, 6).Value = Math.Round(support.Y, 0);
            sheet.Cell(row, 7).Value = Math.Round(support.Z, 0);
            sheet.Cell(row, 8).Value = Math.Round(support.DuctWidth, 0);
            sheet.Cell(row, 9).Value = Math.Round(support.SupportWidth, 0);
            sheet.Cell(row, 10).Value = Math.Round(support.RodLength, 0);
            sheet.Cell(row, 11).Value = Math.Round(support.SupportHeight, 0);
            sheet.Cell(row, 12).Value = Math.Round(support.LoadKg, 1);
            sheet.Cell(row, 13).Value = support.RecommendedRod;
            sheet.Cell(row, 14).Value = support.ClashStatus;
            
            row++;
        }
        
        // Format as table
        var range = sheet.Range(1, 1, row - 1, headers.Length);
        var table = range.CreateTable("SupportSchedule");
        table.Theme = XLTableTheme.TableStyleLight9;
        
        sheet.Columns().AdjustToContents();
    }
    
    /// <summary>
    /// Create load summary sheet for structural coordination.
    /// </summary>
    private void CreateLoadSheet(XLWorkbook workbook, ReportData data)
    {
        var sheet = workbook.Worksheets.Add("Load Summary");
        
        // Header
        sheet.Cell("A1").Value = "STRUCTURAL LOAD SUMMARY";
        sheet.Cell("A1").Style.Font.Bold = true;
        sheet.Cell("A1").Style.Font.FontSize = 14;
        
        // Instructions
        sheet.Cell("A3").Value = "Point loads for structural engineer coordination:";
        
        // Headers
        string[] headers = { "Mark", "Level", "X (mm)", "Y (mm)", "Load (kg)", "Load (lbs)", "Rod Size" };
        
        for (int i = 0; i < headers.Length; i++)
        {
            sheet.Cell(5, i + 1).Value = headers[i];
        }
        
        var headerRow = sheet.Row(5);
        headerRow.Style.Font.Bold = true;
        headerRow.Style.Fill.BackgroundColor = XLColor.LightBlue;
        
        // Data - only ceiling supports have structural loads on ceiling
        int row = 6;
        foreach (var support in data.Supports
            .Where(s => s.Type == "Ceiling")
            .OrderBy(s => s.LevelName)
            .ThenBy(s => s.Mark))
        {
            sheet.Cell(row, 1).Value = support.Mark;
            sheet.Cell(row, 2).Value = support.LevelName;
            sheet.Cell(row, 3).Value = Math.Round(support.X, 0);
            sheet.Cell(row, 4).Value = Math.Round(support.Y, 0);
            sheet.Cell(row, 5).Value = Math.Round(support.LoadKg, 1);
            sheet.Cell(row, 6).Value = Math.Round(support.LoadKg * 2.205, 1); // Convert to lbs
            sheet.Cell(row, 7).Value = support.RecommendedRod;
            row++;
        }
        
        // Total
        row++;
        sheet.Cell(row, 4).Value = "TOTAL:";
        sheet.Cell(row, 4).Style.Font.Bold = true;
        sheet.Cell(row, 5).FormulaA1 = $"=SUM(E6:E{row - 1})";
        sheet.Cell(row, 5).Style.Font.Bold = true;
        
        sheet.Columns().AdjustToContents();
    }
}
